namespace Modificus.Curator.Mods;

/// <summary>
/// A single mod in the global repository: one <c>(source, identity)</c> pair
/// holding zero or more <see cref="ModVersion"/>s. The aggregate root persisted
/// to <c>&lt;ModsFolder&gt;/&lt;Id&gt;/container.json</c>.
/// </summary>
/// <remarks>
/// <para>Identity is <see cref="Id"/> (a <see cref="Guid"/>, stable across
/// renames); the on-disk container directory is keyed by it. <see cref="Name"/>
/// is the display label (set at import, used for the symlink name at stage time,
/// sanitized on use). <see cref="Source"/> records where the mod came from
/// (Untracked / Nexus).</para>
/// <para>
/// Different source-types are separate namespaces: an untracked "WeaponTweaks"
/// and a Nexus "WeaponTweaks" never collide (they are distinct containers, by
/// <see cref="Id"/>). Container identity by source: Nexus by
/// <see cref="NexusSource.ModId"/>, Untracked by <see cref="Name"/> (the source
/// record itself carries no payload).</para>
/// <para>
/// <b>The container's on-disk path is derived</b>:
/// <c>&lt;ModsFolder&gt;/&lt;Id&gt;/</c>. It is never stored absolute, so
/// moving the repository is a physical move of the tree plus a config
/// update (no manifest rewriting, no drift detection).</para>
/// <para>
/// Immutable record: mutations go through <see cref="IModRepository"/>
/// (<c>CreateContainer</c>/<c>AddVersion</c>/<c>RemoveVersion</c>), which
/// rebuild + persist the <c>container.json</c> manifest.</para>
/// </remarks>
public sealed record ModContainer
{
    /// <summary>
    /// Stable identity; also the on-disk container directory name
    /// (<c>&lt;ModsFolder&gt;/&lt;Id&gt;/</c>). Generated by
    /// <see cref="IModRepository.CreateContainer"/>.
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// Where this mod came from (Untracked / Nexus). Default
    /// <see cref="UntrackedSource"/>. For Untracked, this record carries no
    /// identity; the dedup key is <see cref="Name"/>.
    /// </summary>
    public ModSource Source { get; init; } = new UntrackedSource();

    /// <summary>
    /// The display name (set at import). Used for the symlink name at stage
    /// time (sanitized on use). For an untracked container this is also the
    /// dedup key on re-import.
    /// </summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>
    /// The container's imported versions, in storage order. One of them may
    /// carry <see cref="ModVersion.IsLatest"/> (the newest by the
    /// effective-timestamp key; see <see cref="ModVersion.IsLatest"/>); the
    /// repository maintains the invariant. Exposed as an immutable
    /// <see cref="IReadOnlyList{T}"/>: mutations go through
    /// <see cref="IModRepository"/>.
    /// </summary>
    public IReadOnlyList<ModVersion> Versions { get; init; } = Array.Empty<ModVersion>();

    /// <summary>
    /// Optional source-agnostic display metadata (summary, thumbnail URL,
    /// adult-content flag) for a richer row presentation. <c>null</c> means
    /// Curator has not retrieved display metadata; a non-null object with an
    /// empty <see cref="ModDisplayMetadata.Summary"/> and <c>null</c>
    /// <see cref="ModDisplayMetadata.ThumbnailUrl"/> is an authoritative
    /// fetched result with no display content. Initialized only through
    /// <see cref="IModRepository.TryInitializeDisplayMetadata"/> (missing-only)
    /// or set at import via
    /// <see cref="IModRepository.AddVersion"/>; <see cref="IModRepository.AddVersion"/>
    /// with a <c>null</c> metadata argument preserves the prior value, so a
    /// manual re-import never erases a prior Nexus acquisition or backfill.
    /// Backward compatible on disk: a manifest from before this field existed
    /// deserializes it to <c>null</c>.
    /// </summary>
    public ModDisplayMetadata? DisplayMetadata { get; init; }

    /// <summary>
    /// Resolves the version a profile entry should stage, given its policy.
    /// <see cref="LatestPolicy"/> → the container's <see cref="ModVersion.IsLatest"/>
    /// version; <see cref="PinnedPolicy"/> → the version whose
    /// <see cref="ModVersion.Folder"/> matches the pin's
    /// <see cref="PinnedPolicy.VersionId"/> exactly (raw ordinal string equality
    /// on the opaque version id). Returns <c>null</c> when there is no match (the
    /// container has no versions, no <see cref="ModVersion.IsLatest"/> entry,
    /// or the pinned id is not present); the caller skips + warns.
    /// </summary>
    /// <remarks>
    /// Pure: no I/O. Centralizes the resolution used by both staging
    /// (<c>ProfileService.PrepareModRoot</c>) and the startup prune
    /// (<c>ModCleanup.PruneUnreferenced</c>), so the two paths cannot drift.
    /// Resolution is by <see cref="ModVersion.Folder"/> (the version's identity),
    /// never by <see cref="ModVersion.VersionString"/> (the display tag): the
    /// repository is the single source of truth for version details, so a pin
    /// references a version by id, not by tag.
    /// </remarks>
    public ModVersion? ResolveVersion(ModVersionPolicy policy)
    {
        ArgumentNullException.ThrowIfNull(policy);
        return policy switch
        {
            LatestPolicy => Versions.FirstOrDefault(v => v.IsLatest),
            PinnedPolicy pinned => Versions.FirstOrDefault(v =>
                string.Equals(v.Folder, pinned.VersionId, StringComparison.Ordinal)),
            _ => null,
        };
    }
}
